server:
  port: 2002

spring:
  application: 
    name: rabbit-produce-springboot
  rabbitmq:
    username: rabbit
    password: 123456
    port: 5672
    addresses: 127.0.0.1
    virtual-host: /
    #开启发送失败返回
    publisher-returns: true
    #开启发送确认
    publisher-confirms: true
    listener:
      simple:
        #指定最小的消费者数量.
        concurrency: 2
        #指定最大的消费者数量.
        max-concurrency: 2
        #开启ack
        acknowledge-mode: manual
      #开启ack
      direct:
        acknowledge-mode: manual
    #支持消息的确认与返回
    template:
      mandatory: true